### ISSUE TITLE
Might be dropping valid pokemon

### ISSUE THREAD

**Issue by Ni42** [Sjaakmoes/nearby-pokemon-notifier#1]
So, we talked about why this might miss some pokemon. I think it's because of this: https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/models.py#L407

TimeTillHiddenMs is sometimes returned as an invalid (negative or very large) value from the server, but the pokemon are still there. These are capped to 15 minutes instead of dropping them altogether on the pogomap, so it might be worth doing that here too. I can supply a pull request probably tomorrow, if you like.

**Comment by Droeftoeter** [comment]
Haha oops. I fixed that yesterday but forgot to commit. See: https://github.com/Droeftoeter/nearby-pokemon-notifier/commit/3fc54dd0ff534bc23b31f395b8e30111b26289f6 
It defaults to 15 minutes if the time till hidden is weird.

**Edit: derp, committed a print_r.** 
**Edit 2: Fixed**

**Comment by Ni42** [comment]
Awesome. Also nice print_r() in there ;)

**Comment by Droeftoeter** [comment]
Fixed ;)
